"""Initial tables

Revision ID: 19be39213157
Revises: 45a329d1e304
Create Date: 2025-04-27 15:20:59.067015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19be39213157'
down_revision: Union[str, None] = '45a329d1e304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_posts', 'vedio_url')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('blog_posts', sa.Column('vedio_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
